Refresh patches.drivers/0006-efi_pstore-Introducing-workqueue-updating-sysfs.patch. Fix build error:
  CC [M]  net/9p/error.o
drivers/firmware/efivars.c:1697: error: redefinition of
‘variable_is_present’
make[2]: *** [drivers/firmware/efivars.o] Error 1
make[1]: *** [drivers/firmware] Error 2
make: *** [drivers] Error 2
  CC [M]  lib/cpu-notifier-error-inject.o

Because variable_is_present function already merged in
patches.kernel.org/patch-3.0.71-72.